cloudinary:
  api-key: 856348575983318
  api-secret: kC5WgRrhF-rnK0hiOe7mtBuuZm8
  cloud-name: anduala
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # Put here your user name
    username: root
    # Put here your password
    password: ''
    url: jdbc:mysql://localhost:3306/natures_way_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
  jpa:
    #For MySQL 8 uncomment bellow (comment MySQL 5)
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5 (innodb dialect below)
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true